In [1]:
import pandas as pd
import numpy as np

In [94]:
df_data = pd.read_csv('dataR2.csv')

In [3]:
df_test = pd.read_csv('test.csv')

In [4]:
df_data.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

In [22]:
df_data.BMI = df_data.BMI.apply(round, args=[4])
df_data.HOMA = df_data.HOMA.apply(round, args=[4])
df_data.Adiponectin = df_data.Adiponectin.apply(round, args=[4])
df_data.Resistin = df_data.Resistin.apply(round, args=[4])

In [23]:
df_data['Soma'] = [np.sum(d) for d in df_data.drop('Classification', axis=1).values]

In [7]:
df_test['Soma'] = [np.sum(t) for t in df_test.drop('id', axis=1).values]

In [92]:
test_ids = [59, 11, 46, 93, 63, 73, 86, 78, 77, 68, 57, 17, 53, 8, 104, 89, 18, 31, 30, 9, 54, 6, 59, 115, 96]

In [97]:
df_data = df_data.iloc[test_ids, :].sort_values(by='Age')

In [98]:
df_data = df_data.reset_index()

In [65]:
df_test = df_test.sort_values(by='Age')

In [77]:
df_test = df_test.reset_index()
df_test

,index,id,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Soma
0,1,78,29,23.0100,82,5.663,1.1454,35.5900,26.7200,4.5800,174.800,382.5084
1,9,48,43,31.2500,103,4.328,1.0996,25.7816,12.7190,38.6531,775.322,1035.1533
2,3,113,44,27.8876,99,9.208,2.2486,12.6757,5.4782,23.0331,407.206,630.7372
3,21,59,45,20.8300,74,4.560,0.8324,7.7529,8.2374,28.0323,382.955,572.2000
4,16,53,46,20.8300,88,3.420,0.7424,12.8700,18.5500,13.5600,301.210,505.1824
5,8,31,48,31.2500,199,12.162,5.9699,18.1314,4.1041,53.6308,1698.440,2070.6882
6,6,89,49,20.9566,94,12.305,2.8531,11.2406,8.4122,23.1177,573.630,795.5152
7,13,11,49,32.4619,134,24.887,8.2260,42.3914,10.7939,5.7680,656.393,963.9212
8,20,14,51,22.8928,103,2.740,0.6961,8.0163,9.3498,11.5549,359.232,568.4819
9,5,84,53,36.7902,101,10.175,2.5349,27.1841,20.0300,10.2631,695.754,956.7313
10,17,63,57,34.8381,95,12.548,2.9404,33.1612,2.3650,9.9542,655.834,903.6409
11,15,71,58,29.1545,139,16.582,5.6854,22.8884,10.2627,13.9740,923.886,1219.4330
12,22,58,61,32.0390,85,18.077,3.7901,30.7729,7.7803,13.6839,444.395,696.5382
13,0,100,62,22.6562,92,3.482,0.7902,9.8648,11.2362,10.6955,703.973,916.6979
14,14,76,64,34.5297,95,4.427,1.0374,21.2117,5.4626,6.7019,252.449,484.8193
15,23,85,66,31.2386,82,4.181,0.8457,16.2247,4.2671,3.2918,634.602,842.6509
16,7,56,68,21.0828,102,6.200,1.5599,9.6994,8.5747,13.7424,448.799,679.6582
17,12,21,72,23.6200,105,4.420,1.1448,21.7800,17.8600,4.8200,195.940,446.5848
18,18,60,73,22.0000,97,3.350,0.8015,4.4700,10.3587,6.2844,136.855,354.1196
19,4,86,75,23.0000,83,4.952,1.0138,17.1270,11.5790,7.0913,318.302,541.0651
20,2,77,75,25.7000,94,8.079,1.8733,65.9260,3.7412,4.4968,206.802,485.6183
21,10,112,86,27.1800,138,19.910,6.7774,90.2800,14.1100,4.3500,90.090,476.6974
22,11,36,86,26.6667,201,41.611,20.6307,47.6470,5.3571,24.3701,1698.440,2151.7226
23,19,98,89,22.7000,77,4.690,0.8908,6.9640,5.5899,12.9361,1256.083,1475.8538

In [99]:
df_data['id'] = df_test.id

In [100]:
df_data = df_data.iloc[:-1, :]

In [107]:
df_data

,index,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification,id
0,11,29,23.010000,82,5.663,1.145436,35.5900,26.720000,4.58000,174.800,1,78.0
1,77,43,31.250000,103,4.328,1.099601,25.7816,12.718960,38.65310,775.322,2,48.0
2,96,44,27.887617,99,9.208,2.248594,12.6757,5.478170,23.03306,407.206,2,113.0
3,53,45,20.829995,74,4.560,0.832352,7.7529,8.237405,28.03230,382.955,2,59.0
4,68,46,20.830000,88,3.420,0.742368,12.8700,18.550000,13.56000,301.210,2,53.0
5,86,48,28.125000,90,2.540,0.563880,15.5325,10.222310,16.11032,1698.440,2,31.0
6,54,49,20.956608,94,12.305,2.853119,11.2406,8.412175,23.11770,573.630,2,89.0
7,93,49,32.461911,134,24.887,8.225983,42.3914,10.793940,5.76800,656.393,2,11.0
8,63,51,22.892820,103,2.740,0.696143,8.0163,9.349775,11.55492,359.232,2,14.0
9,31,53,36.790166,101,10.175,2.534932,27.1841,20.030000,10.26309,695.754,1,84.0
10,104,57,34.838148,95,12.548,2.940415,33.1612,2.364950,9.95420,655.834,2,63.0
11,89,58,29.154519,139,16.582,5.685415,22.8884,10.262660,13.97399,923.886,2,71.0
12,17,61,32.038959,85,18.077,3.790144,30.7729,7.780255,13.68392,444.395,1,58.0
13,59,62,22.656250,92,3.482,0.790182,9.8648,11.236235,10.69548,703.973,2,100.0
14,59,62,22.656250,92,3.482,0.790182,9.8648,11.236235,10.69548,703.973,2,76.0
15,18,64,34.529723,95,4.427,1.037394,21.2117,5.462620,6.70188,252.449,1,85.0
16,30,66,36.212279,101,15.533,3.869788,74.7069,7.539550,22.32024,864.968,1,56.0
17,57,68,21.082813,102,6.200,1.559920,9.6994,8.574655,13.74244,448.799,2,21.0
18,73,72,23.620000,105,4.420,1.144780,21.7800,17.860000,4.82000,195.940,2,60.0
19,8,73,22.000000,97,3.350,0.801543,4.4700,10.358725,6.28445,136.855,1,86.0
20,46,75,25.700000,94,8.079,1.873251,65.9260,3.741220,4.49685,206.802,1,77.0
21,9,75,23.000000,83,4.952,1.013839,17.1270,11.578990,7.09130,318.302,1,112.0
22,115,86,27.180000,138,19.910,6.777364,90.2800,14.110000,4.35000,90.090,2,36.0
23,78,86,26.666667,201,41.611,20.630734,47.6470,5.357135,24.37010,1698.440,2,98.0

In [108]:
df_data.to_csv('test_data.csv', index=False)

In [93]:
train_ids = [i for i in range(116) if i not in test_ids]

In [95]:
df_train = df_data.iloc[train_ids, :-1]

In [15]:
df_test

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
59,62,22.6562,92,3.482,0.7902,9.8648,11.2362,10.6955,703.973,2
11,29,23.0100,82,5.663,1.1454,35.5900,26.7200,4.5800,174.800,1
96,44,27.8876,99,9.208,2.2486,12.6757,5.4782,23.0331,407.206,2
9,75,23.0000,83,4.952,1.0138,17.1270,11.5790,7.0913,318.302,1
31,53,36.7902,101,10.175,2.5349,27.1841,20.0300,10.2631,695.754,1
54,49,20.9566,94,12.305,2.8531,11.2406,8.4122,23.1177,573.630,2
57,68,21.0828,102,6.200,1.5599,9.6994,8.5747,13.7424,448.799,2
88,48,31.2500,199,12.162,5.9699,18.1314,4.1041,53.6308,1698.440,2
77,43,31.2500,103,4.328,1.0996,25.7816,12.7190,38.6531,775.322,2
115,86,27.1800,138,19.910,6.7774,90.2800,14.1100,4.3500,90.090,2
78,86,26.6667,201,41.611,20.6307,47.6470,5.3571,24.3701,1698.440,2
73,72,23.6200,105,4.420,1.1448,21.7800,17.8600,4.8200,195.940,2
93,49,32.4619,134,24.887,8.2260,42.3914,10.7939,5.7680,656.393,2
18,64,34.5297,95,4.427,1.0374,21.2117,5.4626,6.7019,252.449,1
89,58,29.1545,139,16.582,5.6854,22.8884,10.2627,13.9740,923.886,2
68,46,20.8300,88,3.420,0.7424,12.8700,18.5500,13.5600,301.210,2
8,73,22.0000,97,3.350,0.8015,4.4700,10.3587,6.2844,136.855,1
6,89,22.7000,77,4.690,0.8908,6.9640,5.5899,12.9361,1256.083,1
63,51,22.8928,103,2.740,0.6961,8.0163,9.3498,11.5549,359.232,2
53,45,20.8300,74,4.560,0.8324,7.7529,8.2374,28.0323,382.955,2
17,61,32.0390,85,18.077,3.7901,30.7729,7.7803,13.6839,444.395,1
36,66,31.2386,82,4.181,0.8457,16.2247,4.2671,3.2917,634.602,1
46,75,25.7000,94,8.079,1.8733,65.9260,3.7412,4.4969,206.802,1
104,57,34.8381,95,12.548,2.9404,33.1612,2.3649,9.9542,655.834,2

In [104]:
df_train.to_csv('train_data.csv', index=False)